apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickview

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: clickview
  app.kubernetes.io/managed-by: kustomize
